In [1]:
library(misha) 
library(misha.ext) 
library(tidyverse) 
library(glue) 
library(tgutil) 
gset_genome("mm10")
options(gmax.data.size = 1e9)
options(gmax.data.size = 1e10)
options(gmultitasking = FALSE)
library(tgstat)
library(here)
link_dir =  paste0(here(),'/')
setwd(here())

gsetroot(paste0(link_dir,'data/mm10/'))

gdb.reload()



source(paste0(link_dir,'code/seq2epi_utils.r'))

source(paste0(link_dir,'code/fig_fun.r'))



mod = init_pipe()

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
here() starts at /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_norm

In [7]:
fread('./data/track_cov_atac.txt')

Warning message in data.table::fread(..., data.table = FALSE):
“Detected 8 column names but the data has 9 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

    V1                      Total intervals NaN intervals Min     Max
1   wt_to_wt_epi_eb_d5      136276893       0             0       3146.6987
2   d0_to_I_epi_eb_d5       136276893       0             0       2957.0830
3   d3_to_I_epi_eb_d5       136276893       0             0       3199.1985
4   wt_to_wt_endo_eb_d5     136276893       0             0       3324.9985
5   wt_to_wt_meso_eb_d5     136276893       0             0       2930.0935
6   d0_to_I_endo_eb_d5      136276893       0             0       2211.3882
7   d0_to_I_meso_eb_d5      136276893       0             0       2456.3257
8   d3_to_I_endo_eb_d5      136276893       0             0       3667.2856
9   d3_to_I_meso_eb_d5      136276893       0             0       1144.1494
10  wt_to_wt_eb_d3          136276893       0             0       1363.3521
11  I_to_wt_eb_d3           136276893       0             0       1125.5973
12  I_to_I_eb_d3            136276893       0             0       1638.6899
13  d0_to_I_eb_d3           136276893       0             0       1418.6512
14  dko_to_dko_eb_d3        136276893       0             0        683.1469
15  dko_d0_to_I_eb_d3       136276893       0             0       1346.8027
16  wt_to_wt_eb_d4          136276893       0             0        370.5507
17  I_to_wt_eb_d4           136276893       0             0        225.9493
18  I_to_I_eb_d4            136276893       0             0        139.9499
19  d0_to_I_eb_d4           136276893       0             0        205.9993
20  d3_to_I_eb_d4           136276893       0             0       1210.1976
21  dko_to_dko_eb_d4        136276893       0             0        961.3961
22  dko_d0_to_I_eb_d4       136276893       0             0        993.1469
23  dko_d3_to_I_eb_d4       136276893       0             0        815.5483
24  multieb.ant_ps          136276893       0             0       1007.0000
25  multieb.dppa3           136276893       0             0       2063.0000
26  multieb.epi             136276893       0             0       7761.0000
27  multieb.gut             136276893       0             0       2617.0000
28  multieb.mixed_meso      136276893       0             0        593.0000
29  multieb.nascent_meso    136276893       0             0       2954.0000
30  multieb.ps              136276893       0             0       1369.0000
⋮   ⋮                       ⋮               ⋮             ⋮       ⋮
177 TRP_ATAC_rep1           136276893              0      0.00000 1153.5499
178 PcGDKO_TAM_ATAC_rep2    136276893              0      0.00000 1100.6039
179 EEDcKO_DOX_ATAC_rep1    136276893              0      0.00000 1460.1479
180 RING1Bfl_UNT_ATAC_rep4  136276893              0      0.00000 1479.7487
181 EEDcKO_UNT_ATAC_rep1    136276893              0      0.00000 1071.8036
182 EEDcKO_DOX_ATAC_rep2    136276893              0      0.00000 1208.9979
183 RING1Bfl_UNT_ATAC_rep2  136276893              0      0.00000 1178.0978
184 RING1Bfl_UNT_ATAC_rep3  136276893              0      0.00000 1244.2972
185 PcGDKO_TAM_ATAC_rep3    136276893              0      0.00000 1088.3539
186 RING1Bfl_UNT_ATAC_rep1  136276893              0      0.00000 1059.0045
187 PcGDKO_TAM_ATAC_rep1    136276893              0      0.00000  710.0985
188 DMSO_ATAC_rep2          136276893              0      0.00000  922.5523
189 RING1Bfl_TAM_ATAC_rep1  136276893              0      0.00000  803.2517
190 PcGDKO_UNT_ATAC_rep2    136276893              0      0.00000  935.5530
191 DMSO_ATAC_rep3          136276893              0      0.00000 1487.4979
192 DMSO_ATAC_rep1          136276893              0      0.00000  912.8029
193 PcGDKO_UNT_ATAC_rep1    136276893              0      0.00000  500.6008
194 RING1Bfl_TAM_ATAC_rep2  136276893              0      0.00000 1016.2521
195 TRP_ATAC_rep2           136276893              0      0.00000  688.5008
196 PcGDKO_UNT_ATAC_rep4    136276893              0      0.00000  858.8536
197 RING1Bfl_TAM_ATAC_rep3  136276893              0      0.00000  975.9511
198 PcGDKO_UNT_ATAC_rep3    136276893              0      0.00000  830.7527
199 RING1Bfl_TAM_MNase_rep1 136276893              0      0.00000  882.8016
200 RING1Bfl_UNT_MNase_rep2 136276893              0      0.00000  798.6523
201 RING1Bfl_TAM_MNase_rep3 136276893              0      0.00000  805.8520
202 RING1Bfl_UNT_MNase_rep1 136276893              0      0.00000  817.1017
203 RING1Bfl_UNT_MNase_rep3 136276893              0      0.00000  750.7518
204 RING1Bfl_UNT_Tn5Control 136276893              0      0.00000  750.7518
205 RING1Bfl_TAM_MNase_rep2 136276893              0      0.00000  740.7520
206 ES_ATAC21               136276893       54184190      0.25747 1716.6180
    Sum         Mean        Std dev   V9
1    48006506.4 0.352271800 4.1646698 10934919.28
2    41057269.0 0.301278288 3.8673213  8789717.45
3    36954741.7 0.271173938 3.8083036  8177972.80
4    65952296.9 0.483958032 4.9173838 13870886.48
5    62339087.0 0.457444293 4.6269237 13835677.31
6    63840417.3 0.468461057 4.7133834 15754304.77
7    57333126.9 0.420710552 4.9468393 16029697.09
8    68168623.3 0.500221437 5.2241550 13215977.73
9    19889350.1 0.145948075 1.6730298  6050110.33
10   33500854.5 0.245829309 2.3221788  6702501.91
11   17068577.3 0.125249240 1.4935081  3456737.54
12   39257957.6 0.288074939 2.7179367  7344604.16
13   33665879.6 0.247040264 2.3919490  6765986.06
14    5998556.7 0.044017416 0.7298326  1113332.65
15   28416680.1 0.208521632 2.0739200  5650235.50
16    2961853.6 0.021734085 0.3327492   537487.05
17     875323.8 0.006423127 0.1730446   153558.80
18     501689.5 0.003681398 0.1084471    96794.15
19     931949.5 0.006838647 0.1567278   206243.45
20   27716223.9 0.203381683 2.0247272  5830706.39
21   14261713.0 0.104652467 1.1424657  2494899.25
22   20886132.6 0.153262466 1.4750487  4064354.06
23    9406165.6 0.069022454 0.8563044  1755931.30
24   12723384.0 0.093364207 0.6452030  2081884.00
25   34247494.0 0.251308151 1.6435181  5618965.00
26  128999582.0 0.946599083 6.0576901 21855349.00
27   30843324.0 0.226328348 1.6424527  5625037.00
28    6769396.0 0.049673836 0.4161371  1335923.00
29   38570192.0 0.283028114 1.9132693  6821838.00
30   19667072.0 0.144316997 0.9990935  3462042.00
⋮   ⋮           ⋮           ⋮         ⋮
177  36722437   0.2694693   1.4814914 2046160.8
178  27723249   0.2034332   1.4890406 1945729.3
179  29756438   0.2183528   1.7794343 1839142.8
180  21971512   0.1612270   1.9220405 1811652.2
181  24651889   0.1808956   1.3872133 1697485.5
182  26637220   0.1954639   1.5235740 1686355.0
183  25580799   0.1877119   1.5623979 1629376.4
184  25898267   0.1900415   1.6207801 1699602.1
185  25972728   0.1905879   1.4262129 1669162.2
186  25058298   0.1838778   1.4310448 1745406.7
187  23866501   0.1751324   1.0356369 1493263.2
188  27410829   0.2011407   1.2815615 1452392.0
189  24518988   0.1799204   1.1352889 1492424.0
190  22124560   0.1623500   1.2450607 1246821.6
191  26610774   0.1952699   1.9059514 1261544.3
192  23653979   0.1735729   1.2156470 1162671.9
193  22825209   0.1674914   0.7794093 1152332.9
194  22995325   0.1687397   1.3667915 1159928.6
195  20382814   0.1495691   0.9372852 1210742.2
196  16872676   0.1238117   1.0687252 1042779.8
197  15283764   0.1121523   1.2687830  971094.9
198  16834678   0.1235329   1.0505063  960875.7
199 132042686   0.9689294   1.0365272  378298.9
200 123353539   0.9051684   0.9886081  366499.0
201 111566354   0.8186740   0.9237025  325255.6
202 101614736   0.7456490   0.8706957  304661.4
203 101117568   0.7420008   0.8646585  294655.3
204 101117568   0.7420008   0.8646585  294655.3
205  88776710   0.6514436   0.7956312  264685.7
206  81601182   0.9940126   3.1919248 7167627.9

In [8]:
mod$epi_tracks_atac

    tr_atac
1   or_rk_sf.emb_marginal
2   or_rk_sf.emb_marginal_regcap
3   or_rk_sf.marginal
4   or_rk_sf.marginal_regcap
5   or_rk_sf.rnp
6   or_rk_sf.pmeso
7   or_rk_sf.all
8   jk.epipcg.multieb_prc2i_c.marginal
9   jk.epipcg.multieb_d2prc2i_Id2tCntrl.marginal
10  or_rk_sf.card_meso
11  or_rk_sf.ery3
12  jk.epipcg.multieb_prc2i_i.marginal
13  or_rk_sf.cnp
14  or_rk_sf.ery2
15  or_rk_sf.lmeso
16  or_rk_sf.ac_prog
17  or_rk_sf.cmeso
18  or_rk_sf.tb_n
19  jk.epipcg.multieb_d2prc2i_d2tI.marginal
20  jk.epipcg.lit.zhang_natcom23.marginal
21  or_rk_sf.exe_ve
22  or_rk_sf.nt
23  or_rk_sf.ery1
24  jk.epipcg.multieb_prc2i_c_sub.marginal
25  or_rk_sf.haem_prog
26  or_rk_sf.cepi
27  or_rk_sf.fb_mb_hb
28  jk.epipcg.multieb.marginal
29  jk.epipcg.multieb24.marginal
30  jk.epipcg.multieb_d2prc2i_Id2tCntrl.mcepi2
⋮   ⋮
220 jk.epipcg.multieb_prc2i_c_dinuc.mcLate_nascent_mesoderm
221 jk.epipcg.multieb_prc2i_c.mcSurface_ectoderm
222 jk.epipcg.atac.CRJK_0393_atac_dko_to_dko_eb_d3
223 mut_multi.WT_E75.noto
224 mut_multi.WT_E70.rnp
225 mut_multi.WT_E75.ve
226 jk.epipcg.multieb_prc2i_c.mcVisceral_endoderm
227 mut_multi.WT_E75.haem_prog
228 jk.epipcg.multieb_prc2i_c_nuc.mcMissing
229 jk.epipcg.multieb_prc2i_c_sub.mcMissing
230 jk.epipcg.multieb24_dinuc.mcps
231 jk.epipcg.multieb_prc2i_c_dinuc.mcHaematoendothelial_progenitors
232 jk.epipcg.multieb_prc2i_c.mcepi4_w
233 jk.epipcg.multieb_d2prc2i_Id2tCntrl.mcahnak_epi
234 jk.epipcg.multieb_prc2i_c_nuc.mcSurface_ectoderm
235 jk.epipcg.atac.CRJK_0395_atac_wt_to_wt_eb_d4
236 jk.epipcg.multieb_prc2i_i.mcahnak_nepi
237 jk.epipcg.multieb24_dinuc.mca_ps
238 jk.epipcg.multieb_prc2i_c_sub.mcSurface_ectoderm
239 jk.epipcg.multieb_prc2i_c_nuc.mcVisceral_endoderm
240 jk.epipcg.multieb_prc2i_c_sub.mcVisceral_endoderm
241 jk.epipcg.multieb_prc2i_c_dinuc.mcNode_Notochord
242 jk.epipcg.multieb_prc2i_i.mcepi4_w
243 jk.epipcg.multieb24_dinuc.mcm_meso
244 jk.epipcg.multieb_prc2i_c_dinuc.mcMissing
245 jk.epipcg.atac.CRJK_0398_atac_d0_to_I_eb_d4
246 jk.epipcg.atac.CRJK_0396_atac_I_to_wt_eb_d4
247 jk.epipcg.multieb_prc2i_c_dinuc.mcSurface_ectoderm
248 jk.epipcg.multieb_prc2i_c_dinuc.mcVisceral_endoderm
249 jk.epipcg.atac.CRJK_0397_atac_I_to_I_eb_d4
    short_name                                             cov
1   ofir.emb_marginal                                      1321481143
2   ofir.emb_marginal_regcap                                739128789
3   ofir.marginal                                           384003188
4   ofir.marginal_regcap                                    219715825
5   ofir.rnp                                                178319363
6   ofir.pmeso                                              141300560
7   ofir.all                                                135485335
8   multieb_prc2i_c.marginal                                132354265
9   Id2tCntrl.marginal                                      126870306
10  ofir.card_meso                                          123860238
11  ofir.ery3                                               122171494
12  multieb_prc2i_i.marginal                                122103299
13  ofir.cnp                                                115807545
14  ofir.ery2                                               110327415
15  ofir.lmeso                                              107687213
16  ofir.ac_prog                                            107635004
17  ofir.cmeso                                              105133898
18  ofir.tb_n                                                99035941
19  d2tI.marginal                                            93139769
20  zhang_natcom23.marginal                                  89361543
21  ofir.exe_ve                                              82052223
22  ofir.nt                                                  81983234
23  ofir.ery1                                                80438609
24  multieb_prc2i_c_sub.marginal                             76458767
25  ofir.haem_prog                                           75373131
26  ofir.cepi                                                75040130
27  ofir.fb_mb_hb                                            74611375
28  multieb.marginal                                         71996878
29  multieb24.marginal                                       71996878
30  Id2tCntrl.mcepi2                                         67507430
⋮   ⋮                                                      ⋮
220 multieb_prc2i_c_dinuc.mcLate_nascent_mesoderm          1258835.7
221 multieb_prc2i_c.mcSurface_ectoderm                     1213821.4
222 dko_to_dko_eb_d3                                       1199711.3
223 WT_E75.noto                                            1145586.8
224 WT_E70.rnp                                             1123049.8
225 WT_E75.ve                                              1112734.2
226 multieb_prc2i_c.mcVisceral_endoderm                    1088423.7
227 WT_E75.haem_prog                                       1076188.7
228 multieb_prc2i_c_nuc.mcMissing                          1037940.4
229 multieb_prc2i_c_sub.mcMissing                           983185.9
230 multieb24_dinuc.mcps                                    864088.1
231 multieb_prc2i_c_dinuc.mcHaematoendothelial_progenitors  830800.8
232 multieb_prc2i_c.mcepi4_w                                751839.7
233 Id2tCntrl.mcahnak_epi                                   723454.9
234 multieb_prc2i_c_nuc.mcSurface_ectoderm                  607521.3
235 wt_to_wt_eb_d4                                          592370.7
236 multieb_prc2i_i.mcahnak_nepi                            573087.2
237 multieb24_dinuc.mca_ps                                  563562.3
238 multieb_prc2i_c_sub.mcSurface_ectoderm                  542415.4
239 multieb_prc2i_c_nuc.mcVisceral_endoderm                 539229.0
240 multieb_prc2i_c_sub.mcVisceral_endoderm                 489224.0
241 multieb_prc2i_c_dinuc.mcNode_Notochord                  471829.2
242 multieb_prc2i_i.mcepi4_w                                442526.5
243 multieb24_dinuc.mcm_meso                                314102.4
244 multieb_prc2i_c_dinuc.mcMissing                         270863.2
245 d0_to_I_eb_d4                                           186389.9
246 I_to_wt_eb_d4                                           175064.8
247 multieb_prc2i_c_dinuc.mcSurface_ectoderm                152226.9
248 multieb_prc2i_c_dinuc.mcVisceral_endoderm               139522.9
249 I_to_I_eb_d4                                            100337.9
    ribo_c     take_inh_bulk take_inh_mult V7 take track_k4 take2
1   10707327.0 0             0             NA 0    NA       0
2     505763.8 0             0             NA 0    NA       0
3    3141016.0 0             0             NA 0    NA       0
4     141989.3 0             0             NA 0    NA       0
5     896611.0 0             0             NA 0    NA       1
6     662075.0 0             0             NA 0    NA       1
7     616727.0 0             0             NA 0    NA       0
8     890995.0 0             0             NA 0    NA       0
9     825289.0 0             0             NA 0    NA       0
10    564976.0 0             0             NA 0    NA       0
11    674749.0 0             0             NA 0    NA       0
12    808702.0 0             0             NA 0    NA       0
13    494627.0 0             0             NA 0    NA       0
14    596890.0 0             0             NA 0    NA       0
15    435957.0 0             0             NA 0    NA       1
16    527129.0 0             0             NA 0    NA       1
17    444803.0 0             0             NA 0    NA       0
18    406350.0 0             0             NA 0    NA       0
19    580137.0 0             0             NA 0    NA       0
20    435483.0 0             0             NA 0    NA       0
21    392555.0 0             0             NA 0    NA       0
22    314095.0 0             0             NA 0    NA       0
23    385711.0 0             0             NA 0    NA       0
24    629910.0 0             0             NA 0    NA       0
25    292512.0 0             0             NA 0    NA       1
26    304861.0 0             0             NA 0    NA       0
27    278448.0 0             0             NA 0    NA       0
28    438796.0 0             0             NA 0    NA       0
29    438796.0 0             0             NA 0    NA       0
30    383090.0 0             0             NA 0    NA       0
⋮   ⋮          ⋮             ⋮             ⋮  ⋮    ⋮        ⋮
220 1159.00    0             0             NA 0    NA       0
221 2375.00    0             0             NA 0    NA       0
222 8052.75    0             0             NA 0    NA       0
223 2388.00    0             0             NA 0    NA       0
224 2099.00    0             0             NA 0    NA       0
225 3109.00    0             0             NA 0    NA       0
226 2350.00    0             0             NA 0    NA       0
227 2480.00    0             0             NA 0    NA       0
228 1260.00    0             0             NA 0    NA       0
229 3216.00    0             0             NA 0    NA       0
230  836.00    0             0             NA 0    NA       0
231  780.00    0             0             NA 0    NA       0
232 2032.00    0             0             NA 0    NA       0
233 1413.00    0             0             NA 0    NA       0
234  641.00    0             0             NA 0    NA       0
235 3727.55    0             0             NA 0    NA       0
236 1098.00    0             0             NA 0    NA       0
237  511.00    0             0             NA 0    NA       0
238 1609.00    0             0             NA 0    NA       0
239  606.00    0             0             NA 0    NA       0
240 1641.00    0             0             NA 0    NA       0
241  372.00    0             0             NA 0    NA       0
242  770.00    0             0             NA 0    NA       0
243  290.00    0             0             NA 0    NA       0
244  237.00    0             0             NA 0    NA       0
245 1497.35    0             0             NA 0    NA       0
246 1208.25    0             0             NA 0    NA       0
247  125.00    0             0             NA 0    NA       0
248  103.00    0             0             NA 0    NA       0
249  734.45    0             0             NA 0    NA       0

In [17]:
fread('./data/colors.txt')

   celltype                       colour        layer
1  Parietal endoderm              #1A1A1A       Ext
2  ExE ectoderm                   #989898       Ext
3  ExE mesoderm                   #8870ad       ExeMeso
4  ExE endoderm                   #7F6874       Ext
5  Visceral endoderm              #F6BFCB       Ext
6  Gut                            #EF5A9D       Endo
7  Notochord                      #0F4A9C       Endo
8  Def. endoderm                  #F397C0       Endo
9  Anterior Primitive Streak      #c19f70       Endo
10 PGC                            #FACB12       PGC
11 Sox1Tead2                      chartreuse3   Invitro
12 Dppa3                          darkkhaki     Invitro
13 ESC                            antiquewhite3 Invitro
14 ESC_Zscan                      antiquewhite1 Invitro
15 Epiblast                       #635547       Epi
16 Primitive Streak               #DABE99       MesoEndo
17 Caudal epiblast                #9e6762       EctoMeso
18 Caudal neurectoderm            #354E23       Ecto
19 Rostral neurectoderm           #65A83E       Ecto
20 Surface ectoderm               #f7f79e       Ecto
21 Forebrain/Midbrain/Hindbrain   #647a4f       Ecto
22 Spinal cord                    #CDE088       Ecto
23 NMP                            #8EC792       Ecto
24 Nascent mesoderm               #C594BF       Meso
25 Mixed mesoderm                 #DFCDE4       Meso
26 Intermediate mesoderm          #139992       Meso
27 Pharyngeal mesoderm            #C9EBFB       Meso
28 Paraxial mesoderm              #8DB5CE       Meso
29 Somitic mesoderm               #005579       Meso
30 Caudal Mesoderm                #3F84AA       Meso
31 Allantois                      #532C8A       ExeMeso
32 Mesenchyme                     #cc7818       ExeMeso
33 Cardiomyocytes                 #B51D8D       Meso
34 Haematoendothelial progenitors #FBBE92       Heme
35 Endothelium                    #ff891c       Heme
36 Blood progenitors 1            #f9decf       Heme
37 Blood progenitors 2            #c9a997       Heme
38 Erythroid1                     #C72228       Heme
39 Erythroid2                     #f79083       Heme
40 Erythroid3                     #EF4E22       Heme

In [22]:
atac_meta

    tr_atac                                      short_name           cov
29  jk.epipcg.multieb24.marginal                 multieb24.marginal   71996878
54  jk.epipcg.multieb24.mcEpiblast               multieb24.mcEpiblast 38484243
147 jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3 wt_to_wt_eb_d3        6700171
    ribo_c take_inh_bulk take_inh_mult V7 take
29  438796 0             0             NA 0
54  190455 0             0             NA 0
147  48802 1             0             NA 1
    track_k4                                           take2
29  NA                                                 0
54  NA                                                 0
147 jk.epipcg.pcg.CRJK_0411_k4me3_wt_to_wt_eb_d3_a70ls 0

In [57]:
library("tglkmeans")

In [67]:
gdb.reload()

In [70]:
gtrack.ls('jk.epipcg.atac')

[1] "jk.epipcg.atac.CRJK_0373_atac_wt_to_wt_epi_eb_d5"
[2] "jk.epipcg.atac.CRJK_0373_atac_wt_to_wt_epi_eb_d5_regcap"
[3] "jk.epipcg.atac.CRJK_0376_atac_wt_to_wt_endo_eb_d5"
[4] "jk.epipcg.atac.CRJK_0376_atac_wt_to_wt_endo_eb_d5_regcap"
[5] "jk.epipcg.atac.CRJK_0377_atac_wt_to_wt_meso_eb_d5"
[6] "jk.epipcg.atac.CRJK_0377_atac_wt_to_wt_meso_eb_d5_regcap"
[7] "jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3"
[8] "jk.epipcg.atac.CRJK_0400_atac_dko_to_dko_eb_d4"

In [71]:
tracks_atac = c('jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3','jk.epipcg.atac.CRJK_0373_atac_wt_to_wt_epi_eb_d5',
'jk.epipcg.atac.CRJK_0377_atac_wt_to_wt_meso_eb_d5','jk.epipcg.atac.CRJK_0376_atac_wt_to_wt_endo_eb_d5')


tracks_f = tracks_atac

atac_meta = mod$track_atac_ribo
atac_meta = atac_meta[atac_meta$tr_atac %in% tracks_f, ,drop=F]
atac_meta = atac_meta[match(tracks_f, atac_meta$tr_atac), ]
ribo = atac_meta$ribo_c
tr_dsamp_r = min(ribo)/ribo
names(tr_dsamp_r) = atac_meta$short_name


#print(tr_dsamp_r)
for (tr in atac_meta$tr_atac) {
        gvtrack.create(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
            tr, "sum")
        #gvtrack.iterator(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
        #    sshift = -140, eshift = 140)
    }



meta_ucsc = data.frame(track = atac_meta$tr_atac,cell_type_id=1:nrow(atac_meta), 
           cell_type = atac_meta$short_name,
           color = c('#635547','#635547','#C594BF','#EF5A9D'), 
           shorthand=atac_meta$short_name)

###downsampled smoothed celltype tracks  




df <- meta_ucsc[ meta_ucsc$track %in% atac_meta$tr_atac,]
plyr::a_ply(df, 1, function(x){
       
        r_ds = tr_dsamp_r[ x$shorthand]
        print(r_ds)
        data <- gextract(x$shorthand, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0
        to_ds = matrix(data$score, ncol = 1)
        post_ds = downsample_matrix(to_ds, target_n = floor(sum(to_ds) *
                  r_ds), seed = 19)
        data$score = post_ds
        data$score = log2(data$score+1)
        print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{x$shorthand}.ucsc"),
                   name = x$shorthand, description = x$shorthand, type="wig", span = 20, color = x$color)
    })

wt_to_wt_eb_d3
             1
     20%      50%      98%      99%    99.5%
0.000000 0.000000 4.954196 6.022368 6.906891
wt_to_wt_epi_eb_d5
         0.6011942
     20%      50%      98%      99%    99.5%
0.000000 0.000000 4.643856 5.832890 6.794416
wt_to_wt_meso_eb_d5
          0.4529383
     20%      50%      98%      99%    99.5%
0.000000 0.000000 4.584963 5.754888 6.714246
wt_to_wt_endo_eb_d5
          0.4586734
     20%      50%      98%      99%    99.5%
0.000000 0.000000 4.700440 5.832890 6.754888

In [69]:
tracks_atac = c('jk.epipcg.multieb.epi',
'jk.epipcg.multieb.nascent_meso','jk.epipcg.multieb.gut')


tracks_f = tracks_atac

atac_meta = mod$track_atac_ribo
atac_meta = atac_meta[atac_meta$tr_atac %in% tracks_f, ,drop=F]
atac_meta = atac_meta[match(tracks_f, atac_meta$tr_atac), ]
ribo = atac_meta$ribo_c
tr_dsamp_r = min(ribo)/ribo
names(tr_dsamp_r) = atac_meta$short_name


#print(tr_dsamp_r)
for (tr in atac_meta$tr_atac) {
        gvtrack.create(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
            tr, "sum")
        #gvtrack.iterator(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
        #    sshift = -140, eshift = 140)
    }



meta_ucsc = data.frame(track = atac_meta$tr_atac,cell_type_id=1:nrow(atac_meta), 
           cell_type = atac_meta$short_name,
           color = c('#635547','#C594BF','#EF5A9D'), 
           shorthand=atac_meta$short_name)

###downsampled smoothed celltype tracks  




df <- meta_ucsc[ meta_ucsc$track %in% atac_meta$tr_atac,]
plyr::a_ply(df, 1, function(x){
       
        r_ds = tr_dsamp_r[ x$shorthand]
        print(r_ds)
        data <- gextract(x$shorthand, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0
        to_ds = matrix(data$score, ncol = 1)
        post_ds = downsample_matrix(to_ds, target_n = floor(sum(to_ds) *
                  r_ds), seed = 19)
        data$score = post_ds
        data$score = log2(data$score+1)
        print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{x$shorthand}.ucsc"),
                   name = x$shorthand, description = x$shorthand, type="wig", span = 20, color = x$color)
    })

multieb.epi
  0.2579244
     20%      50%      98%      99%    99.5%
0.000000 1.000000 4.754888 5.781360 6.599913
multieb.nascent_meso
           0.8173544
     20%      50%      98%      99%    99.5%
0.000000 1.000000 4.523562 5.523562 6.409391
multieb.gut
          1
     20%      50%      98%      99%    99.5%
0.000000 1.000000 4.523562 5.523562 6.392317

In [63]:
tracks_atac = c('jk.epipcg.multieb24.mcEpiblast',
'jk.epipcg.multieb24.mcGut','jk.epipcg.multieb24.mcn_meso')


tracks_f = tracks_atac

atac_meta = mod$track_atac_ribo
atac_meta = atac_meta[atac_meta$tr_atac %in% tracks_f, ,drop=F]
atac_meta = atac_meta[match(tracks_f, atac_meta$tr_atac), ]
ribo = atac_meta$ribo_c
tr_dsamp_r = min(ribo)/ribo
names(tr_dsamp_r) = atac_meta$short_name

In [65]:
atac_meta$tr_atac

[1] "jk.epipcg.multieb24.mcEpiblast" "jk.epipcg.multieb24.mcGut"
[3] "jk.epipcg.multieb24.mcn_meso"

In [58]:


#print(tr_dsamp_r)
for (tr in atac_meta$tr_atac) {
        gvtrack.create(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
            tr, "sum")
        #gvtrack.iterator(atac_meta[atac_meta$tr_atac == tr, ]$short_name,
        #    sshift = -140, eshift = 140)
    }



meta_ucsc = data.frame(track = atac_meta$tr_atac,cell_type_id=1:nrow(atac_meta), 
           cell_type = atac_meta$short_name,
           color = c('#635547','#C594BF','#EF5A9D'), 
           shorthand=atac_meta$short_name)

###downsampled smoothed celltype tracks  




df <- meta_ucsc[ meta_ucsc$track %in% atac_meta$tr_atac,]
plyr::a_ply(df, 1, function(x){
       
        r_ds = tr_dsamp_r[ x$shorthand]
        print(r_ds)
        data <- gextract(x$shorthand, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0
        to_ds = matrix(data$score, ncol = 1)
        post_ds = downsample_matrix(to_ds, target_n = floor(sum(to_ds) *
                  r_ds), seed = 19)
        data$score = post_ds
        data$score = log2(data$score+1)
        print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{x$shorthand}.ucsc"),
                   name = x$shorthand, description = x$shorthand, type="wig", span = 20, color = x$color)
    })

multieb24.mcEpiblast
            0.339235
     20%      50%      98%      99%    99.5%
0.000000 1.000000 5.129283 6.169925 6.988685

Warning message:
“Using one column matrices in `filter()` was deprecated in dplyr 1.1.0.
ℹ Please use one dimensional logical vectors instead.
ℹ The deprecated feature was likely used in the misha.ext package.
  Please report the issue to the authors.”

multieb24.mcGut
              1
     20%      50%      98%      99%    99.5%
0.000000 1.000000 4.906891 5.930737 6.781360
multieb24.mcn_meso
         0.9021335
     20%      50%      98%      99%    99.5%
0.000000 1.000000 4.906891 5.930737 6.794416

 [1] "at.EB4_norm_300"
 [2] "jk.epipcg.pcg.CRJK_0211_k27me3_es_50k_norm"
 [3] "jk.epipcg.pcg.CRJK_0232_k27me3_es_2i_dmso_norm"
 [4] "jk.epipcg.pcg.CRJK_0293_k27me3_j1_eb_d5_epi_norm"
 [5] "jk.epipcg.pcg.CRJK_0294_k27me3_j1_eb_d5_meso_norm"
 [6] "jk.epipcg.pcg.CRJK_0321_k27me3_e75_ecto_norm"
 [7] "jk.epipcg.pcg.CRJK_0324_k27me3_e75_e_meso_norm"
 [8] "jk.epipcg.pcg.CRJK_0363_k27me3_eb_j1_d3_a_norm"
 [9] "jk.epipcg.pcg.CRJK_0364_k27me3_eb_j1_d4_a_norm"
[10] "jk.epipcg.pcg.CRJK_0365_k27me3_eb_dko_d3_a_norm"
[11] "jk.epipcg.pcg.CRJK_0408_k27me3_dko_to_dko_eb_d4_norm"
[12] "jk.epipcg.pred.eb4_xgb_pred_norm"
[13] "seq.IQ.pcg.borzoi.finetune_norm_128k_EB4_cnt_cropped"
[14] "seq.IQ.pcg.borzoi.finetune_norm_128k_EB4_cnt_k4_cropped"
[15] "seq.IQ.pcg.borzoi.finetune_norm_16k_EB4_cnt_cropped"
[16] "seq.IQ.pcg.borzoi.finetune_norm_16k_EB4_cnt_k4_cropped"
[17] "seq.IQ.pcg.borzoi.finetune_norm_1k_EB4_cnt_cropped"
[18] "seq.IQ.pcg.borzoi.finetune_norm_1k_EB4_cnt_k4_cropped"
[19] "seq.IQ.pcg.borzoi.finetune_norm_256k_EB4_cnt_cropped"
[20] "seq.IQ.pcg.borzoi.finetune_norm_256k_EB4_cnt_k4_cropped"
[21] "seq.IQ.pcg.borzoi.finetune_norm_2k_EB4_cnt_cropped"
[22] "seq.IQ.pcg.borzoi.finetune_norm_2k_EB4_cnt_k4_cropped"
[23] "seq.IQ.pcg.borzoi.finetune_norm_32k_EB4_cnt_cropped"
[24] "seq.IQ.pcg.borzoi.finetune_norm_32k_EB4_cnt_k4_cropped"
[25] "seq.IQ.pcg.borzoi.finetune_norm_4k_EB4_cnt_cropped"
[26] "seq.IQ.pcg.borzoi.finetune_norm_4k_EB4_cnt_k4_cropped"
[27] "seq.IQ.pcg.borzoi.finetune_norm_524k_EB4_cnt_cropped"
[28] "seq.IQ.pcg.borzoi.finetune_norm_524k_EB4_cnt_k4_cropped"
[29] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_EB4_cnt_cropped"
[30] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_EB4_cnt_k4_cropped"
[31] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_mouse_EB4_cnt_cropped"
[32] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_mouse_EB4_cnt_k4_cropped"
[33] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_mouse_mm10_EB4_cnt_cropped"
[34] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_mouse_mm10_EB4_cnt_k4_cropped"
[35] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_EB4_cnt_cropped"
[36] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_EB4_cnt_k4_cropped"
[37] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_mm10_EB4_cnt_cropped"
[38] "seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_mm10_EB4_cnt_k4_cropped"
[39] "seq.IQ.pcg.borzoi.finetune_norm_64k_EB4_cnt_cropped"
[40] "seq.IQ.pcg.borzoi.finetune_norm_64k_EB4_cnt_k4_cropped"
[41] "seq.IQ.pcg.borzoi.finetune_norm_8k_EB4_cnt_cropped"
[42] "seq.IQ.pcg.borzoi.finetune_norm_8k_EB4_cnt_k4_cropped"
[43] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_cre_epi.finetune_norm_524k_EB4_cnt_cropped"
[44] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_cre_epi.finetune_norm_524k_EB4_cnt_k4_cropped"
[45] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_cre_marginal.finetune_norm_524k_EB4_cnt_cropped"
[46] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_cre_marginal.finetune_norm_524k_EB4_cnt_k4_cropped"
[47] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_ctcf_with_cre_epi.finetune_norm_524k_EB4_cnt_cropped"
[48] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_ctcf_with_cre_epi.finetune_norm_524k_EB4_cnt_k4_cropped"
[49] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_ctcf.finetune_norm_524k_EB4_cnt_cropped"
[50] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_ctcf.finetune_norm_524k_EB4_cnt_k4_cropped"
[51] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250.finetune_norm_524k_EB4_cnt_cropped"
[52] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250.finetune_norm_524k_EB4_cnt_k4_cropped"
[53] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_ctcf.finetune_norm_524k_EB4_cnt_cropped"
[54] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_ctcf.finetune_norm_524k_EB4_cnt_k4_cropped"

In [63]:
gvtrack.create('EB5_epi_cnt_n', 'jk.epipcg.pcg.CRJK_0293_k27me3_j1_eb_d5_epi_norm', 
        "avg")
gvtrack.iterator('EB5_epi_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('EB3_cnt_n', 'jk.epipcg.pcg.CRJK_0363_k27me3_eb_j1_d3_a_norm', 
        "avg")
gvtrack.iterator('EB3_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('ES_2i_cnt_n', 'jk.epipcg.pcg.CRJK_0232_k27me3_es_2i_dmso_norm', 
        "avg")
gvtrack.iterator('ES_2i_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('ES_cnt_n', 'jk.epipcg.pcg.CRJK_0211_k27me3_es_50k_norm', 
        "avg")
gvtrack.iterator('ES_cnt_n', sshift = -500, eshift = 500)



gvtrack.create('EB5_epi_cnt_n', 'jk.epipcg.pcg.CRJK_0293_k27me3_j1_eb_d5_epi_norm', 
        "avg")
gvtrack.iterator('EB5_epi_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('EB5_meso_cnt_n', 'jk.epipcg.pcg.CRJK_0294_k27me3_j1_eb_d5_meso_norm', 
        "avg")
gvtrack.iterator('EB5_meso_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('e75_ecto_cnt_n', 'jk.epipcg.pcg.CRJK_0321_k27me3_e75_ecto_norm', 
        "avg")
gvtrack.iterator('e75_ecto_cnt_n', sshift = -500, eshift = 500)


gvtrack.create('e75_emeso_cnt_n', 'jk.epipcg.pcg.CRJK_0324_k27me3_e75_e_meso_norm', 
        "avg")
gvtrack.iterator('e75_emeso_cnt_n', sshift = -500, eshift = 500)

In [2]:
 gvtrack.create("flash_noCGD_k27", "seq.IQ.pcg.flashzoi.mm10MinusCGD.rf524k_EB4_cnt", 
        "avg")
gvtrack.iterator("flash_noCGD_k27", sshift = -500, eshift = 500)
 gvtrack.create("flash_noCGD_k4", 'seq.IQ.pcg.flashzoi.mm10MinusCGD.rf524k_EB4_cnt_k4', 
        "sum")
    gvtrack.iterator("flash_noCGD_k4", sshift = -140, eshift = 140)

In [24]:
gtrack.ls('noX')

[1] "jk.epipcg.pred.eb4_xgb_lm_10test_seeds_gc_cg_noX"

In [25]:
gvtrack.create("sns_lm", 'jk.epipcg.pred.eb4_xgb_lm_10test_seeds_gc_cg_noX', 
        "avg")
gvtrack.iterator("sns_lm", sshift = -500, eshift = 500)

In [29]:
gdb.reload()

In [21]:
gtrack.ls('rf524k_EB4_cnt')

[1] "seq.IQ.pcg.flashzoi.mm10.rf524k_EB4_cnt"
[2] "seq.IQ.pcg.flashzoi.mm10.rf524k_EB4_cnt_k4"
[3] "seq.IQ.pcg.flashzoi.mm10MinusCGD.rf524k_EB4_cnt"
[4] "seq.IQ.pcg.flashzoi.mm10MinusCGD.rf524k_EB4_cnt_k4"

In [ ]:
"seq.IQ.pcg.flashzoi.mm10.rf524k_EB4_cnt"

"seq.IQ.pcg.fm.mm10.rf524k_EB4_cnt"

In [27]:

gvtrack.create("flash524_k27", "seq.IQ.pcg.flashzoi.mm10.rf524k_EB4_cnt", 
        "avg")
gvtrack.iterator("flash524_k27", sshift = -500, eshift = 500)

In [30]:

gvtrack.create("fm524_k27", "seq.IQ.pcg.fm.mm10.rf524k_EB4_cnt" , 
        "avg")
gvtrack.iterator("fm524_k27", sshift = -500, eshift = 500)

In [61]:
mod$cgdom_ann[ mod$cgdom_ann$tss_gene=='Utf1',]

      chrom start     end       l    eb3_k27_max eb4_k27_max eb4_k27_mean
24620 chr7  139943666 139945075 1409 100.25      7.653001    6.860797
      eb4_k4_max eb4_k4_mean l6_eb4_k4_mean ⋯ ltr simp low_complex tot_rpt
24620 258.15     220.3472    7.822394       ⋯ 0   0    0           0
      tss_dist tss_strand tss_start tss_gene type ID
24620 0        1          139943666 Utf1     cl2  16597

In [45]:
cg_trace = readRDS('/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_norm/data/cg_trace_mm10.rds')
f_norp = cg_trace$d_ltr != 0 & cg_trace$d_line != 0 & cg_trace$start > 3e+06
cg_trace_f = cg_trace[f_norp,c('chrom','start','end')]

dim(gintervals.canonic(cg_trace_f))
dim((cg_trace_f))
cg_trace_f = gintervals.canonic(cg_trace_f)

cg_trace_f$score = 1
cg_trace_f$intervalID = 1:nrow(cg_trace_f)
tr =  'f_repeat'   
color = 'purple'
df = cg_trace_f


# df has columns: chrom, start, end, score, intervalID

# Convert to UCSC BED (0-based start)
bed <- data.frame(
  chrom = as.character(df$chrom),
  chromStart = as.integer(df$start) - 1,   # UCSC BED: 0-based start
  chromEnd = as.integer(df$end),
  name = paste0("interval_", df$intervalID),
  score = pmax(0L, pmin(1000L, as.integer(round(df$score * 1000)))) # UCSC score 0-1000
)

# If your df$score is already fine as 0-1000, use this instead:
# bed$score <- pmax(0L, pmin(1000L, as.integer(df$score)))

out_bed <- "./ucsc_tracks/f_norp_ucsc_track.bed"

# Write with a UCSC track line at the top
track_line <- 'track name="f_norp" description="f_norp" visibility=2 itemRgb="On"'

con <- file(out_bed, open = "wt")
writeLines(track_line, con)
write.table(bed, con, sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
close(con)

message("Wrote: ", normalizePath(out_bed))

[1] 908921      3

[1] 8310621       3

Wrote: /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks/f_norp_ucsc_track.bed

In [42]:
head(df)

  chrom start end  score intervalID
1 chr1     0   200 1     1
2 chr1   200   400 1     2
3 chr1   400   600 1     3
4 chr1   600   800 1     4
5 chr1   800  1000 1     5
6 chr1  1000  1200 1     6

In [6]:
borz_folds = gintervals.load("borzoi.folds")
btrain = borz_folds[borz_folds$type == "train",]
btrainc = gintervals.canonic(btrain)

In [16]:
head(btrainc)
btrainc$score = 1
btrainc$intervalID = 1:nrow(btrainc)
tr =  'borzoi_train'   
color = 'purple'
df = btrainc



# df has columns: chrom, start, end, score, intervalID

# Convert to UCSC BED (0-based start)
bed <- data.frame(
  chrom = as.character(df$chrom),
  chromStart = as.integer(df$start) - 1,   # UCSC BED: 0-based start
  chromEnd = as.integer(df$end),
  name = paste0("interval_", df$intervalID),
  score = pmax(0L, pmin(1000L, as.integer(round(df$score * 1000)))) # UCSC score 0-1000
)

# If your df$score is already fine as 0-1000, use this instead:
# bed$score <- pmax(0L, pmin(1000L, as.integer(df$score)))

out_bed <- "./ucsc_tracks/borzoi_train_ucsc_track.bed"

# Write with a UCSC track line at the top
track_line <- 'track name="borzoi_train" description="borzoi_train" visibility=2 itemRgb="On"'

con <- file(out_bed, open = "wt")
writeLines(track_line, con)
write.table(bed, con, sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
close(con)

message("Wrote: ", normalizePath(out_bed))

  chrom start    end      score intervalID
1 chr1   7858555  9038623 1     1
2 chr1   9072414 17530086 1     2
3 chr1  17569429 21208147 1     3
4 chr1  21211007 22391075 1     4
5 chr1  22466510 25908536 1     5
6 chr1  25909751 35105018 1     6

Wrote: /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks/borzoi_train_ucsc_track.bed

In [47]:
gdb.reload()

In [48]:
gtrack.ls('meso')

 [1] "jk.epipcg.atac.CRJK_0377_atac_wt_to_wt_meso_eb_d5"
 [2] "jk.epipcg.atac.CRJK_0377_atac_wt_to_wt_meso_eb_d5_regcap"
 [3] "jk.epipcg.multieb24.mcn_meso"
 [4] "jk.epipcg.pcg.CRJK_0294_k27me3_j1_eb_d5_meso"
 [5] "jk.epipcg.pcg.CRJK_0294_k27me3_j1_eb_d5_meso_norm"
 [6] "jk.epipcg.pcg.CRJK_0323_k27me3_e75_meso"
 [7] "jk.epipcg.pcg.CRJK_0324_k27me3_e75_e_meso"
 [8] "jk.epipcg.pcg.CRJK_0324_k27me3_e75_e_meso_norm"
 [9] "jk.epipcg.pcg.CRJK_0361_k27me3_e7_meso"
[10] "jk.epipcg.pred.eb4_xgb_meso_cres"
[11] "jk.epipcg.pred.eb4_xgb_meso_no_cres"
[12] "mut_multi.WT_E75.exe_meso"
[13] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250_with_ctcf.finetune_524k_e75_emeso_cnt_no_atac_cropped"
[14] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_CGD_exp250.finetune_524k_e75_emeso_cnt_no_atac_cropped"
[15] "seq.IQ.pcg.borzoi.mus_silicus_cg_gc_lower_with_ctcf.finetune_524k_e75_emeso_cnt_no_atac_cropped"

In [49]:
gvtrack.create("sns_meso_no_cres", 'jk.epipcg.pred.eb4_xgb_meso_no_cres', 
        "avg")
gvtrack.iterator("sns_meso_no_cres", sshift = -500, eshift = 500)

tr =  "sns_meso_no_cres"   
color = 'blue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
0.000000 4.942835 5.455812 5.814328 6.248781

In [72]:
gdb.reload()

In [73]:
"jk.epipcg.pred.eb4_xgb_meso_cres_atac"
gvtrack.create("sns_meso_cres_atac", "jk.epipcg.pred.eb4_xgb_meso_cres_atac", 
        "avg")
gvtrack.iterator("sns_meso_cres_atac", sshift = -500, eshift = 500)

tr =  "sns_meso_cres_atac"   
color = 'darkviolet'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

[1] "jk.epipcg.pred.eb4_xgb_meso_cres_atac"

     20%      50%      98%      99%    99.5%
0.000000 4.944654 5.468941 5.817896 6.253079

In [ ]:
gvtrack.create("sns_meso_cres", 'jk.epipcg.pred.eb4_xgb_meso_cres', 
        "avg")
gvtrack.iterator("sns_meso_cres", sshift = -500, eshift = 500)

tr =  "sns_meso_cres"   
color = 'blue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

In [62]:
gvtrack.create("sns_meso_cres_base", 'jk.epipcg.pred.eb4_xgb_meso_cres_base', 
        "avg")
gvtrack.iterator("sns_meso_cres_base", sshift = -500, eshift = 500)

tr =  "sns_meso_cres_base"   
color = 'blue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
0.000000 4.942616 5.433238 5.794332 6.219076

In [26]:
tr =  'sns_lm'   
color = 'blue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
0.000000 4.869467 5.948685 6.374483 6.808053

In [31]:
tr =  'flash524_k27'   
color = 'darkgreen'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
5.314414 5.374612 6.877800 7.468571 8.023044

In [32]:
tr =  'fm524_k27'   
color = 'brown'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
5.000616 5.081771 6.478726 6.991506 7.495683

In [4]:
tr =  'flash_noCGD_k27'   
color = 'darkviolet'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
5.322850 5.374908 6.356571 6.626879 6.893971

In [5]:
tr =  'flash_noCGD_k4'   
color = 'pink'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

         20%          50%          98%          99%        99.5%
  0.01221389   0.19344933 154.98313965 331.77032227 613.67834229

In [70]:
tr =  'e75_emeso_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.940680 4.978881 5.515347 6.036870 6.843846

In [69]:
tr =  'e75_ecto_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.845767 4.964375 6.193524 6.725180 7.372422

In [68]:
tr =  'EB5_meso_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.903659 4.953785 5.724061 6.302780 7.029361

In [67]:
tr =  'EB5_epi_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.881432 4.960739 5.818099 6.305527 6.859891

In [66]:
tr =  'EB3_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.742826 4.846507 6.459107 6.920421 7.334688

In [65]:
tr =  'ES_2i_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.813053 4.874105 6.125361 6.557276 6.958756

In [64]:
tr =  'ES_cnt_n'   
color = 'darkblue'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

   print(quantile(data$score,c(.2,.5,.98,.99,.995)))
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

     20%      50%      98%      99%    99.5%
4.903920 4.943064 5.637498 6.044695 6.523692

In [50]:
data <- gextract('EB4_cnt', gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0

In [51]:
quantile(data$score,c(.2,.5,.98,.99,.995))

     20%      50%      98%      99%    99.5%
4.752667 4.840858 6.474416 7.051327 7.599620

In [40]:
mod$epi_tracks_cnt

   track_k27
1  jk.epipcg.pcg.CRJK_0211_k27me3_es_50k
2  jk.epipcg.pcg.CRJK_0232_k27me3_es_2i_dmso
3  jk.epipcg.pcg.CRJK_0363_k27me3_eb_j1_d3_a
4  jk.epipcg.pcg.CRJK_0365_k27me3_eb_dko_d3_a
5  jk.epipcg.pcg.CRJK_0407_k27me3_dko_to_dko_eb_d3
6  jk.epipcg.pcg.CRJK_0403_k27me3_wt_to_wt_eb_d3
7  jk.epipcg.pcg.CRJK_0408_k27me3_dko_to_dko_eb_d4
8  jk.epipcg.pcg.CRJK_0364_k27me3_eb_j1_d4_a_norm
9  jk.epipcg.pcg.CRJK_0361_k27me3_e7_meso
10 jk.epipcg.pcg.CRJK_0321_k27me3_e75_ecto
11 jk.epipcg.pcg.CRJK_0324_k27me3_e75_e_meso
12 jk.epipcg.pcg.CRJK_0293_k27me3_j1_eb_d5_epi
13 jk.epipcg.pcg.CRJK_0294_k27me3_j1_eb_d5_meso
14 jk.epipcg.pcg.CRJK_0295_k27me3_j1_eb_d5_endo
   track_k4
1  NA
2  NA
3  NA
4  NA
5  jk.epipcg.pcg.CRJK_0413_k4me3_dko_to_dko_eb_d3
6  jk.epipcg.pcg.CRJK_0411_k4me3_wt_to_wt_eb_d3
7  jk.epipcg.pcg.CRJK_0414_k4me3_dko_to_dko_eb_d4
8  NA
9  NA
10 NA
11 NA
12 NA
13 NA
14 NA
   track_ub
1  jk.epipcg.pcg.CRJK_0221_h2ak119u1_es_dmso_d7
2  jk.epipcg.pcg.CRJK_0233_h2ak119u1_es_2i_dmso
3  jk.epipcg.pcg.CRJK_0225_h2ak119u1_eb_dmso_d3
4
5
6
7
8  jk.epipcg.pcg.CRJK_0229_h2ak119u1_eb_dmso_d4
9
10
11
12
13
14
   track_ub_inh
1  jk.epipcg.pcg.CRJK_0237_h2ak119u1_es_prc2i_d14
2  jk.epipcg.pcg.CRJK_0235_h2ak119u1_p2_2i_prc2i
3  jk.epipcg.pcg.CRJK_0227_h2ak119u1_eb_prc2i_d3
4
5
6
7
8  jk.epipcg.pcg.CRJK_0231_h2ak119u1_eb_prc2i_d4
9
10
11
12
13
14
   track_k4me1
1
2
3
4
5
6
7
8
9
10 jk.epipcg.pcg.CRJK_0360_k4me1_e7_ecto_a70ls
11
12
13
14
   atac                                           type short_name
1  jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3   CnT  ES_cnt
2  jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3   CnT  ES2i_cnt
3  jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3   CnT  EB3_cnt
4  jk.epipcg.atac.CRJK_0400_atac_dko_to_dko_eb_d4 CnT  EB3_dko_1
5  jk.epipcg.atac.CRJK_0400_atac_dko_to_dko_eb_d4 CnT  EB3_dko_t_dko
6  jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3   CnT  EB3_wt_t_wt
7  jk.epipcg.atac.CRJK_0400_atac_dko_to_dko_eb_d4 CnT  EB4_dko_t_dko
8  jk.epipcg.atac.CRJK_0389_atac_wt_to_wt_eb_d3   CnT  EB4_cnt
9  mut_multi.WT_E70.marginal                      CnT  e7_meso
10 mut_multi.WT_E75.epi                           CnT  e75_ecto_cnt
11 mut_multi.WT_E75.exe_meso                      CnT  e75_emeso_cnt
12                                                CnT  EB5_epi_cnt
13                                                CnT  EB5_meso_cnt
14                                                CnT  EB5_endo_cnt
   short_name_k4 use_comb inh dko in_vivo take
1  0              1       NA  NA  NA      1
2  0              1       NA  NA  NA      1
3  0             NA       NA  NA  NA      1
4  0             NA       NA   1  NA      0
5  EB3_dko_t_dko NA       NA   1  NA      0
6  EB3_wt_t_wt   NA       NA  NA  NA      1
7  EB4_dko_t_dko NA       NA   1  NA      0
8  0              1       NA  NA  NA      1
9  0             NA       NA  NA   1      1
10 0              1       NA  NA   1      1
11 0              1       NA  NA   1      1
12 0             NA       NA  NA  NA      1
13 0             NA       NA  NA  NA      1
14 0             NA       NA  NA  NA      1

In [44]:
        gvtrack.create('EB4_cnt_k4',
            'jk.epipcg.pcg.CRJK_0411_k4me3_wt_to_wt_eb_d3', "sum")
    #    gvtrack.iterator('EB4_cnt_k4',
      #      sshift = -140, eshift = 140)

In [57]:
tr =  'EB4_cnt_k4' 
color = 'darkred'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0
        data$score = log2(1+data$score)
   
        fwrite_ucsc(data, file = glue::glue("~/raid_dir/Proj/polycomb/seq2epi_paper_norm/ucsc_tracks//{tr}.ucsc"),
                   name = tr, description = tr, type="wig", span = 20, color = color)

In [56]:
tr =  'EB4_cnt_k4' 
color = 'darkred'
data <- gextract(tr, gintervals.all(),iterator = 300, colnames = "score")
        data$score[ is.na(data$score)] = 0
data$score = log2(1+data$score)
quantile(data$score,c(.2,.5,.98,.99,.995))

     20%      50%      98%      99%    99.5%
0.000000 0.000000 4.346957 5.658211 6.713558

In [55]:
log2(49.5+1)

[1] 5.658211

In [35]:
gquantiles('EB4_cnt_k4',c(.2,.25,.5,.98,.99,.995))

   0.2   0.25    0.5   0.98   0.99  0.995
  0.00   0.00   0.00  19.35  49.45 103.85

In [ ]:
quantile(mod$gw$cg_trace$lk27_1k,c(.2,.25,.5,.98,.99,.995))
#4.7 6.5

gquantiles('seq.IQ.pcg.borzoi.finetune_norm_524k_EB4_cnt_cropped',c(.2,.25,.5,.98,.99,.995))
#5 6.5

gquantiles('seq.IQ.pcg.borzoi.finetune_norm_524k_silicus_cgd_ctcf_cre_mouse_EB4_cnt_cropped',c(.2,.25,.5,.98,.99,.995))
#5.1 6.27

gquantiles('jk.epipcg.pred.eb4_xgb_brz2k_seeds',c(.2,.25,.5,.98,.99,.995))
#4.8 6.26

gquantiles('jk.epipcg.pred.eb4_xgb_lm_seeds',c(.2,.25,.5,.98,.99,.995))
#4.8 6.16